pub(crate) const SLASH_HELP_LINES: &[&str] = &[
    "Commands:",
    "  /help  /exit  /clear  /compact  /usage  /save  /session",
    "  /paste  /images  /clear-images  /context  /review  /think",
    "",
    "Scrolling:",
    "  Mouse wheel     - scroll 3 lines",
    "  PageUp/PageDown - scroll 10 lines",
    "  Shift+Up/Down   - scroll 1 line",
    "  Shift+Home      - scroll to top",
    "  Shift+End       - scroll to bottom",
    "",
    "Input:",
    "  Enter           - send message",
    "  Alt+Enter       - new line",
    "  Tab             - accept suggestion",
    "  Ctrl+C          - interrupt / exit",
    "  Ctrl+V          - paste image from clipboard",
];
