events {}

http {
  upstream aemeath_http {
    server server:3000;
  }

  upstream aemeath_grpc {
    server server:50051;
  }

  server {
    listen 8080;

    location /api/ {
      proxy_pass http://aemeath_http;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /ws/ {
      proxy_pass http://aemeath_http;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    location /grpc/ {
      grpc_pass grpc://aemeath_grpc;
    }
  }
}
