FROM rust:1.85-bookworm AS builder
WORKDIR /app
COPY . .
RUN cargo build -p server

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/debug/server /usr/local/bin/server
EXPOSE 3000 50051
CMD ["server"]
