//! Tools domain 常量（#1146 双轨归位）。

pub const RUNTIME_META_KEYS: &[&str] = &["phase"];

pub(crate) const CHAIN_START_COMMANDS: &[&str] = &["cd", "pushd", "popd", "dirs"];

pub(crate) const DEDICATED_FILE_READ_COMMANDS: &[&str] = &["cat", "head", "tail"];

pub(crate) const READONLY_COMMANDS: &[&str] = &[
    "ls",
    "cat",
    "head",
    "tail",
    "wc",
    "nl",
    "stat",
    "file",
    "du",
    "df",
    "pwd",
    "whoami",
    "hostname",
    "uname",
    "date",
    "uptime",
    "env",
    "printenv",
    "echo",
    "printf",
    "which",
    "where",
    "type",
    "find",
    "locate",
    "tree",
    "grep",
    "rg",
    "ag",
    "ack",
    "git status",
    "git log",
    "git diff",
    "git show",
    "git branch",
    "git remote",
    "git tag",
    "git blame",
    "git stash list",
    "cargo check",
    "cargo test",
    "cargo clippy",
    "cargo doc",
    "npm test",
    "npm run lint",
    "npx tsc --noEmit",
    "jq",
    "yq",
    "sort",
    "uniq",
    "cut",
    "tr",
    "docker ps",
    "docker images",
    "docker logs",
    "kubectl get",
    "kubectl describe",
    "kubectl logs",
    "gh pr view",
    "gh issue view",
    "man",
    "help",
    "less",
    "more",
];

// ─── shell_safety.rs ───

pub(crate) const SAFE_DEVS: &[&str] = &["/dev/null", "/dev/stdout", "/dev/stderr", "/dev/tty"];
