//! Typed result structs for every tool, plus the small support types they
//! reference. Defined here in `share` so all feature crates
//! (`tools`, `runtime`, `compact`, …) can refer to them without depending on
//! `sdk` (which is a thin re-export / protocol facade — see
//! `docs/design/outline.md` §依赖铁律 and
//! `docs/snapshot/specs/047-ddd-redesign.md` §6.4.7 for the boundary).
//!
//! The same structs are `pub use`-re-exported by `packages/sdk::tool_result`
//! for the `cli` consumer and any future `server` consumer.
//!
//! See `docs/superpowers/plans/2026-06-18-tool-display-structured-data.md`
//! (plan 方案 D) for the design rationale and the per-tool field tables.

// ---------------------------------------------------------------------------
// Support types referenced by more than one tool's result struct.
// Kept in `share` (not in any feature) so the result structs can stay
// `use`-able from any feature without inverting DDD boundaries.
// ---------------------------------------------------------------------------

pub mod support;

/// Trait generated by `#[derive(ToolSchema)]` — provides a JSON Schema
/// describing the `data` field of a tool's result payload.
pub trait ToolSchema {
    fn data_schema() -> serde_json::Value;
}

pub mod read;
pub mod write;
pub mod edit;
pub mod glob;
pub mod grep;
pub mod web_fetch;
pub mod bash;
pub mod agent;
pub mod enter_worktree;
pub mod exit_worktree;
pub mod ask_user;

// Re-exports for ergonomic `use share::tool::types::XxxResult;`.
pub use agent::AgentResult;
pub use ask_user::AskUserQuestionResult;
pub use bash::BashResult;
pub use edit::EditResult;
pub use enter_worktree::EnterWorktreeResult;
pub use exit_worktree::ExitWorktreeResult;
pub use glob::GlobResult;
pub use grep::GrepResult;
pub use read::ReadResult;
pub use web_fetch::WebFetchResult;
pub use write::WriteResult;
// Non-core tool result structs (Phase 0a 任务 0.4).
pub mod brief;
pub mod config_tool;
pub mod list_mcp_resources;
pub mod lsp;
pub mod mcp_manager;
pub mod mcp_tool;
pub mod memory;
pub mod plan_mode;
pub mod read_mcp_resource;
pub mod skill;
pub mod sleep;
pub mod task_create;
pub mod task_get;
pub mod task_list;
pub mod task_list_complete;
pub mod task_list_create;
pub mod task_stop;
pub mod task_update;
pub mod tool_search;
pub mod web_search;

// Re-exports for non-core tool result structs.
pub use brief::BriefResult;
pub use config_tool::ConfigResult;
pub use list_mcp_resources::ListMcpResourcesResult;
pub use lsp::LspResult;
pub use mcp_manager::McpManagerResult;
pub use mcp_tool::McpToolResult;
pub use memory::MemoryResult;
pub use plan_mode::PlanModeResult;
pub use read_mcp_resource::ReadMcpResourceResult;
pub use skill::SkillResult;
pub use sleep::SleepResult;
pub use task_create::TaskCreateResult;
pub use task_get::TaskGetResult;
pub use task_list::TaskListResult;
pub use task_list_complete::TaskListCompleteResult;
pub use task_list_create::TaskListCreateResult;
pub use task_stop::TaskStopResult;
pub use task_update::TaskUpdateResult;
pub use tool_search::ToolSearchResult;
pub use web_search::WebSearchResult;
