import { defineStore } from 'pinia';
import type { AgentSummary, BoardNote, WorkspaceSummary } from '../types';

const workspaces: WorkspaceSummary[] = [
  {
    id: 'feature-36',
    label: 'current',
    title: 'Feature 36 · Multi-Agent',
    meta: '4 requirements · 6 projects · 2 running agents',
    active: true,
  },
  { id: 'cli-tui', label: 'recent', title: 'CLI TUI polish', meta: '12 chats · last updated 18m' },
  { id: 'provider-routing', label: 'recent', title: 'Provider routing', meta: '8 chats · cost tracking' },
];

const agents: AgentSummary[] = [
  {
    id: 'ui-builder',
    label: 'UI Builder Agent',
    title: 'Editing sticky board mockup',
    state: 'running',
    meta: 'tool: Edit',
  },
  {
    id: 'spec-reviewer',
    label: 'Spec Reviewer',
    title: 'Checking BoardSnapshot semantics',
    state: 'blocked',
    meta: 'needs schema',
  },
  { id: 'runtime', label: 'Runtime Agent', title: 'Waiting for assignment', state: 'idle', meta: 'ready' },
];

const notes: BoardNote[] = [
  {
    id: 'req-01',
    kind: 'requirement',
    tone: 'req',
    kicker: 'REQ-01',
    title: 'Board-centric workspace',
    status: 'confirmed',
    statusLabel: '已确认',
    agent: 'UI Builder Agent',
    agentLabel: 'UI Builder',
    description: 'The board should be the primary surface, not a secondary status panel.',
    tasks: ['Accepted by PM', 'Keep side context in drawers', 'Prioritize canvas density'],
  },
  {
    id: 'req-02',
    kind: 'requirement',
    tone: 'req',
    kicker: 'REQ-02',
    title: 'Live agent visibility',
    status: 'draft',
    statusLabel: '草稿',
    agent: 'Spec Reviewer',
    agentLabel: 'Spec',
    description: 'Users can see which agent is working and what artifact it is touching.',
    tasks: ['Show running agents', 'Expose current tool call', 'Display last heartbeat'],
  },
  {
    id: 'req-03',
    kind: 'requirement',
    tone: 'req',
    kicker: 'REQ-03',
    title: 'Focused chat input',
    status: 'confirmed',
    statusLabel: '已确认',
    description: 'Chat remains available but only expands when the user needs to speak.',
    tasks: ['Keep dock collapsed', 'Expand on focus', 'Add quick board actions'],
  },
  {
    id: 'req-04',
    kind: 'requirement',
    tone: 'req',
    kicker: 'REQ-04',
    title: 'Recoverable updates',
    status: 'draft',
    statusLabel: '草稿',
    agent: 'Runtime Agent',
    agentLabel: 'Runtime',
    description: 'Snapshot and delta updates should be visually understandable after reconnect.',
    tasks: ['Mark stale cards', 'Replay missed deltas', 'Summarize recovery'],
  },
  {
    id: 'req-05',
    kind: 'requirement',
    tone: 'req',
    kicker: 'REQ-05',
    title: 'Compact board density',
    status: 'confirmed',
    statusLabel: '已确认',
    description: 'The board should hold many planning objects without turning into a dashboard.',
    tasks: ['Reduce sticky size', 'Hide details by default', 'Use click inspector'],
  },
  {
    id: 'req-06',
    kind: 'requirement',
    tone: 'req',
    kicker: 'REQ-06',
    title: 'Drawer context',
    status: 'draft',
    statusLabel: '草稿',
    agent: 'UI Builder Agent',
    agentLabel: 'UI Builder',
    description: 'Workspace and agent context should remain accessible without stealing center-stage space.',
    tasks: ['Left workspace drawer', 'Right agent drawer', 'No top navigation'],
  },
  {
    id: 'project-01',
    kind: 'project',
    tone: 'project',
    kicker: 'PROJECT-01',
    title: 'Multi-Agent Runtime',
    status: 'running',
    statusLabel: '进行中',
    agent: 'Runtime Agent',
    agentLabel: 'Runtime',
    description: 'A shared board aggregates workspace state, chat threads, task execution and agent lifecycle.',
    tasks: ['Define BoardSnapshot schema', 'Render project cards', 'Connect task assignment'],
  },
  {
    id: 'project-02',
    kind: 'project',
    tone: 'project-green',
    kicker: 'PROJECT-02',
    title: 'Agent Execution View',
    status: 'running',
    statusLabel: '进行中',
    agent: 'UI Builder Agent',
    agentLabel: 'UI Builder',
    description: 'Show active agent work, current tool call, blocking state and last heartbeat.',
    tasks: ['Design running card', 'Add heartbeat indicator', 'Expose cancel affordance'],
  },
  {
    id: 'project-03',
    kind: 'project',
    tone: 'project-pink',
    kicker: 'PROJECT-03',
    title: 'Watch Recovery UX',
    status: 'waiting',
    statusLabel: '等待中',
    description: 'Make reconnects, stale snapshots and replayed deltas understandable without modal noise.',
    tasks: ['Mark stale board objects', 'Replay missed deltas', 'Summarize recovery result'],
  },
  {
    id: 'project-04',
    kind: 'project',
    tone: 'project-violet',
    kicker: 'PROJECT-04',
    title: 'Focused Chat Dock',
    status: 'running',
    statusLabel: '进行中',
    agent: 'UI Builder Agent',
    agentLabel: 'UI Builder',
    description: 'Keep chat available at the bottom while preserving the whiteboard as the primary surface.',
    tasks: ['Prototype focus expansion', 'Add quick board actions', 'Route prompts to selected card'],
  },
  {
    id: 'project-05',
    kind: 'project',
    tone: 'project-amber',
    kicker: 'PROJECT-05',
    title: 'Workspace Graph',
    status: 'waiting',
    statusLabel: '等待中',
    agent: 'Spec Reviewer',
    agentLabel: 'Spec',
    description: 'Represent workspace, chats, messages and board objects as a navigable graph.',
    tasks: ['Map chat to board cards', 'Show relationship lines', 'Support selection focus'],
  },
  {
    id: 'project-06',
    kind: 'project',
    tone: 'project',
    kicker: 'PROJECT-06',
    title: 'Board Inspector',
    status: 'waiting',
    statusLabel: '等待中',
    description: 'Clicking a sticky note opens a focused detail surface instead of expanding every card.',
    tasks: ['Build detail panel', 'Parse note task list', 'Support close state'],
  },
];

export const useBoardStore = defineStore('board', {
  state: () => ({
    workspaces,
    agents,
    notes,
    selectedNoteId: notes[0]?.id ?? '',
  }),
  getters: {
    selectedNote: (state) => state.notes.find((note) => note.id === state.selectedNoteId) ?? state.notes[0],
    requirementNotes: (state) => state.notes.filter((note) => note.kind === 'requirement'),
    projectNotes: (state) => state.notes.filter((note) => note.kind === 'project'),
  },
  actions: {
    selectNote(noteId: string) {
      this.selectedNoteId = noteId;
    },
    clearSelection() {
      this.selectedNoteId = '';
    },
  },
});
