//! TUI 默认主题色。
//!
//! 采用 Catppuccin Macchiato 风格的暗色主题语义色，避免各组件直接散落硬编码颜色。

use super::constants::{ACCENT, ACCENT_BRIGHT, ASSISTANT, BASE, BLUE, BORDER, CODE, DIFF_ADD_FG, DIFF_REMOVE_FG, ERROR, GREEN, LAVENDER, LINK, MACCHIATO_TEXT, MAROON, MAUVE, OVERLAY0, OVERLAY1, OVERLAY2, PEACH, PINK, RED, ROSEWATER, SAPPHIRE, SELECTION_BG, SELECTION_FG, SPINNER_BASE, SPINNER_DIM, SPINNER_HIGHLIGHT, STATUS_BG, SUBTEXT0, SUBTEXT1, SUCCESS, SURFACE, SURFACE0, SURFACE1, SURFACE2, SURFACE_ELEVATED, TEAL, TEXT, TEXT_DIM, TEXT_MUTED, THINKING, TOOL_RUNNING, USER, USER_BG, WARNING, YELLOW};
use ratatui::style::Color;
